config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'prawn' => 'prawn#generate'
  get 'wicked_pdf' => 'wicked_pdf#generate'
  get 'wicked_pdf_to_file' => 'wicked_pdf#generate_to_file'
  get 'pdfkit/generate_manual' => 'pdfkit#generate_manual'
  get 'read_pdf' => 'pdf#read'
  get 'fill_pdf_forms' => 'pdf#fill'

end

app/models/product.rb
class Product
  attr_accessor :id, :name, :price

  def initialize(id, name, price)
    @id = id
    @name = name
    @price = price
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController
  def read
    path = Rails.root.join('public', 'testpdf.pdf')
    @pdf_contents = PdfReader.read(path)
  end

  def fill
    path = Rails.root.join('public', 'testformpdf.pdf')
    filled_pdf_path = FillPdf.new(path, firstname: 'Test').call
    send_file filled_pdf_path
  end
end

app/controllers/pdfkit_controller.rb
class PdfkitController < ApplicationController
  def generate_manual
    kit = PDFKit.new('<b>Manual PDF</b>', page_size: 'Letter')

    respond_to do |format|
      format.html
      format.pdf do
        send_data kit.to_pdf, filename: 'report.pdf', type: 'application/pdf'
      end
    end
  end
end

app/controllers/prawn_controller.rb
class PrawnController < ApplicationController
  def generate
    respond_to do |format|
      format.html
      format.pdf do
        pdf = PrawnReport.new(products)
        send_data pdf.render, filename: 'report.pdf', type: 'application/pdf'
      end
    end
  end

  private

  def products
    [
      Product.new(1, 'Product name', 9.99),
      Product.new(2, 'Product2 name', 19.99),
      Product.new(3, 'Product4 name', 12.23),
    ]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wicked_pdf_controller.rb
class WickedPdfController < ApplicationController
  def generate
    @products = products
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "report", layout: "pdf.html.haml"
      end
    end
  end

  def generate_to_file
    @products = products
    render pdf: 'foo',
       save_to_file: Rails.root.join('tmp', "wicked_report.pdf"),
       save_only: true,
       template: 'wicked_pdf/generate'
    redirect_to root_path, notice: 'PDF generated'
  end

  private

  def products
    [
      Product.new(1, 'Product name', 9.99),
      Product.new(2, 'Product2 name', 19.99),
      Product.new(3, 'Product4 name', 12.23),
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkingWithPdfs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/pdf.html.haml
!!!
%html
  %head
    %title RailsWickedPdf
    = wicked_pdf_stylesheet_link_tag "application", media: "all"
    = wicked_pdf_javascript_include_tag "application"
    = csrf_meta_tags
  %body.wicked_pdf
    = yield

app/views/pdf/read.haml
%h1 Pdf content
%p
  %b version
  = @pdf_contents.version
%p
  %b created_by
  = @pdf_contents.producer
%p
  %b creation_date
  = @pdf_contents.creation_date
%p
  %b page_count
  = @pdf_contents.page_count

app/views/welcome/index.haml
.container
  %h1 Generate PDF
  %ul.nav.nav-pills.nav-stacked
    %li=link_to 'Prawn', prawn_path(format: 'pdf')
    %li=link_to 'Wicked_pdf', wicked_pdf_path(format: 'pdf')
    %li=link_to 'Wicked_pdf to file', wicked_pdf_to_file_path(format: 'pdf')
    %li=link_to 'Pdfkit', pdfkit_generate_manual_path(format: 'pdf')
    %li=link_to 'Read pdf', read_pdf_path
    %li=link_to 'Fill out PDF forms', fill_pdf_forms_path

app/views/wicked_pdf/generate.haml
.container
  .row
    = wicked_pdf_image_tag('header.png')
  .row
    .col-xs-6
      %h3
        Lorem ipsum
      %p
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse interdum semper placerat. Aenean mattis fringilla risus ut fermentum. Fusce posuere dictum venenatis. Aliquam id tincidunt ante, eu pretium eros. Sed eget risus a nisl aliquet scelerisque sit amet id nisi. Praesent porta molestie ipsum, ac commodo erat hendrerit nec. Nullam interdum ipsum a quam euismod, at consequat libero bibendum. Nam at nulla fermentum, congue lectus ut, pulvinar nisl. Curabitur consectetur quis libero id laoreet. Fusce dictum metus et orci pretium, vel imperdiet est viverra. Morbi vitae libero in tortor mattis commodo. Ut sodales libero erat, at gravida enim rhoncus ut.
    .col-xs-6
      %h3
        Duis vel
      %p
        Duis vel tortor elementum, ultrices tortor vel, accumsan dui. Nullam in dolor rutrum, gravida turpis eu, vestibulum lectus. Pellentesque aliquet dignissim justo ut fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut venenatis massa non eros venenatis aliquet. Suspendisse potenti. Mauris sed tincidunt mauris, et vulputate risus. Aliquam eget nibh at erat dignissim aliquam non et risus. Fusce mattis neque id diam pulvinar, fermentum luctus enim porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
  .row
    %table.table.table-striped
      %thead
        %th #
        %th Product
        %th Price
      %tbody
        - @products.each do |product|
          %tr
            %td
              = product.id
            %td
              = product.name
            %td
              = product.price